remote_theme: pmarsceill/just-the-docs
search_enabled: false

logo: /icon-site.png

aux_links:
  Redyn on GitHub:
    - https://github.com/someimportantcompany/redyn

back_to_top: true
back_to_top_text: "Back to top"

footer_content: >
  Copyright © {{ 'now' | date: "%Y" }}.
  Distributed by an [MIT license]({{site.gh_edit_repository}}/blob/master/LICENSE).
  Redyn has no affiliation with [Redis](https://redis.io/documentation/#credits).

gh_edit_link: true
gh_edit_link_text: Edit this page on GitHub
gh_edit_repository: https://github.com/someimportantcompany/redyn
gh_edit_branch: master
gh_edit_source: docs
gh_edit_view_mode: edit
